# Generated by Django 6.1.1 on 2026-10-07 17:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cover_letter', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'NEW'), ('viewed', 'VIEWED'), ('interview', 'INTERVIEW'), ('discard', 'DISCARD')], db_index=True, default='new', max_length=10)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
