# Generated by Django 6.1.1 on 2026-10-03 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_category'),
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='employee',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='employee',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='employee',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='employee',
            new_name='user',
        ),
        migrations.AddField(
            model_name='resume',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseapp.category'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=models.ManyToManyField(to='baseapp.skill'),
        ),
    ]
