# Generated by Django 6.1.1 on 2026-10-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_category'),
        ('resumes', '0002_rename_employee_education_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, to='baseapp.skill'),
        ),
    ]
