# Generated by Django 6.1.1 on 2026-10-04 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_alter_resume_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='langs', to='resumes.resume'),
        ),
    ]
