# Generated by Django 6.1.1 on 2026-10-04 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
        ('resumes', '0004_alter_education_degree'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='language',
            unique_together={('name', 'resume')},
        ),
    ]
