# Generated by Django 6.1.1 on 2026-10-07 17:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0002_initial'),
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'active'), ('BLOCKED', 'blocked')], default='ACTIVE', max_length=30)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='companies.company')),
                ('employee', models.ForeignKey(limit_choices_to={'user_role': 'EMPLOYEE'}, on_delete=django.db.models.deletion.CASCADE, related_name='my_chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('company', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message_type', models.CharField(choices=[('APPLICATION', 'application'), ('DISCARD', 'discard'), ('INTERVIEW', 'interview'), ('ARCHIVE', 'archive'), ('MESSAGE', 'message')], max_length=30)),
                ('context', models.CharField(max_length=10000)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.application')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chat')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
