# Generated by Django 6.1.1 on 2026-10-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.CharField(choices=[('EMPLOYEE', 'employee'), ('COMPANY', 'company')], default='EMPLOYEE', max_length=20),
        ),
    ]
