# Generated by Django 6.1.1 on 2026-10-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(choices=[('EMPLOYEE', 'employee'), ('COMPANY', 'company')], max_length=20),
        ),
    ]
