# Generated by Django 6.1.1 on 2026-10-09 17:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_sender'),
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='employee',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together={('company', 'user')},
        ),
    ]
