# Generated by Django 6.1.1 on 2026-10-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_role',
            field=models.CharField(choices=[('EMPLOYER', 'employer'), ('EMPLOYEE', 'employee')], default='EMPLOYEE', max_length=20),
        ),
    ]
