# Generated by Django 6.1.1 on 2026-10-03 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_role',
            field=models.CharField(choices=[('EMPLOYER', 'employer'), ('EMPLOYEE', 'employee')], max_length=20),
        ),
    ]
