# Generated by Django 6.1.1 on 2026-10-03 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='employer',
            new_name='user',
        ),
    ]
