# Generated by Django 6.1.1 on 2026-10-03 13:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseapp', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=5000)),
                ('requirements', models.CharField(max_length=2000)),
                ('salary_from', models.PositiveIntegerField()),
                ('salary_to', models.PositiveIntegerField()),
                ('experience', models.CharField(max_length=30)),
                ('employement_type', models.CharField(choices=[('ON_SITE', 'on_site'), ('REMOTE', 'remote'), ('HYBRID', 'hybrid')], max_length=50)),
                ('status', models.CharField(choices=[('ACTIVE', 'active'), ('DRAFT', 'draft'), ('ARCHIVED', 'archived')], default='DRAFT', max_length=20)),
                ('published_at', models.DateTimeField(auto_now=True, null=True)),
                ('expires_at', models.DateTimeField(auto_now=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseapp.district')),
                ('skills', models.ManyToManyField(related_name='required_skills', to='baseapp.skill')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
